### ISSUE TITLE
When mob dies this error appears.

### ISSUE THREAD

**Issue by appsbytom** [MCLovesMy/InventoryFilled#28]
[14:44:24 ERROR]: Could not pass event EntityDeathEvent to InventoryFilled v1.4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:363) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:868) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntitySkeleton.die(EntitySkeleton.java:125) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:806) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.Entity.K(Entity.java:312) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.K(EntityLiving.java:167) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityInsentient.K(EntityInsentient.java:149) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.Entity.s_(Entity.java:245) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityLiving.s_(EntityLiving.java:1438) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityInsentient.s_(EntityInsentient.java:193) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.EntityMonster.s_(EntityMonster.java:26) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1604) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.World.g(World.java:1579) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1422) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.bukkit.event.entity.EntityDamageEvent cannot be cast to org.bukkit.event.entity.EntityDamageByEntityEvent
        at com.MCLovesMy.Events.MobKill.onEntityDeath(MobKill.java:38) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        ... 24 more

On 1.8 no idea as to why this is happening. any help would be great

**Comment by daniel-vd** [comment]
Sorry for my long absence. I will continue developing this plugin from now on.

I think this problem has to do with the fact the plugin is outdated, i will update the plugin as soon as possible and try to fix this error.

**Comment by daniel-vd** [comment]
@TheTomTom3901 i have updated the app, you can download the update from spigotmc.org. If the error still appers please open a new issue.
